POST http://localhost:5000/api/blogs
Content-Type: application/json; charset=utf-8
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG5AMTIzIiwiaWQiOjIsImlhdCI6MTY2MzA1OTI3NX0.5IOf1vrCuKG8RezdsxaGFFzpjDzZps8FMF-UOPQIpe4

{
    "author": "Jane Doe",
    "url": "mazenta.com",
    "title": "Mezanta"
}

###
DELETE http://localhost:5000/api/blogs/5
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphbmVAMTIzIiwiaWQiOjIsImlhdCI6MTY2MjgzMjEwMX0.FlmSJIbACpuTyYv_2MpVV3D4mqungZnN_eSHuOTG0e0


###
GET http://localhost:5000/api/blogs/ 

###
POST http://localhost:5000/api/users
Content-Type: application/json; charset=utf-8

{
    "username": "John@123",
    "name": "John Doe"
}

###
GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/login
Content-Type: application/json; charset=utf-8

{ "username": "John@123", "password":"pswd" }